"""add offers table

Revision ID: c4af328831b5
Revises: 2c5b64e63fe7
Create Date: 2026-03-08 19:44:47.342849

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c4af328831b5'
down_revision: Union[str, Sequence[str], None] = '2c5b64e63fe7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('offers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('total_amount', sa.Float(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_offers_company_id'), 'offers', ['company_id'], unique=False)
    op.create_index(op.f('ix_offers_customer_id'), 'offers', ['customer_id'], unique=False)
    op.create_index(op.f('ix_offers_id'), 'offers', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_offers_id'), table_name='offers')
    op.drop_index(op.f('ix_offers_customer_id'), table_name='offers')
    op.drop_index(op.f('ix_offers_company_id'), table_name='offers')
    op.drop_table('offers')
    # ### end Alembic commands ###
